### ISSUE TITLE
References to IBM Enterprise GitHub could be parameterized

### ISSUE THREAD

**Issue by SpaceKatt** [asifmahmud/ansible-git-clone#2]
There exist a few instances where `github.ibm.com` is referenced. I'm assuming this is the IBM enterprise GH server. These references could be parameterized to make the role more flexible for reuse by folk outside of IBM.

Adding something like `GITHUB_SERVER_FQDN` to `vars/main.yml` would do the trick~

https://github.com/asifmahmud/ansible-git-clone/blob/bd38e6201c37bdb176890d81aa31ccebf8481947/tasks/main.yml#L29-L50

**Comment by asifmahmud** [comment]
Hi @SpaceKatt , that's a great idea. I have made the change as you suggested
