### ISSUE TITLE
Problem with this approach: SSH private key remains on the target unencrypted

### ISSUE THREAD

**Issue by pierluigiferrari** [asifmahmud/ansible-git-clone#4]
Thank you for this and your accompanying article [here](https://community.ibm.com/community/user/ibmz-and-linuxone/blogs/asif-mahmud1/2020/03/15/cloning-private-git-repository-using-ansible)!

There is one problem that makes this approach not ideal in practice, this line here:
[`command: "ssh-keygen -t rsa -f {{ KEY_PATH }} -N ''"`](https://github.com/asifmahmud/ansible-git-clone/blob/e1719d553fda5d544075cf6dd2178f7b49e5584e/tasks/main.yml#L9)

It's not safe to have the SSH private key on the target in plain text.

**Comment by asifmahmud** [comment]
Hi @pierluigiferrari , yeah I agree with your concern. I think if we have a clean up step where we remove the generated key from target machine, after we are done cloning the repository, that should mitigate the security concern. What do you think?

**Comment by pierluigiferrari** [comment]
Yeah, for certain cases that might work. I have a case where the remote machines need to access the repository regularly after initially cloning it, and each access needs to be automated, i.e. without someone needing to enter any passwords. For that case I realized your approach is actually equally secure as any other possibility I could choose, because for my scenario some key will inevitably ultimately need to be accessible to the remote machines in plain text -.-
